name: Convert PDF to Markdown

on:
  workflow_dispatch:
  push:
    paths:
    - '**.md'

jobs:
  convert_md: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 1
    - name: install dependency
      run: sudo apt-get update && sudo apt-get install -y fonts-nanum librsvg2-bin pandoc texlive-xetex ko.tex texstudio texlive-latex-base texlive-fonts-recommended texlive-latex-extra
#     - name: donwload pandoc
#       run: wget https://github.com/jgm/pandoc/releases/download/2.13/pandoc-2.13-1-amd64.deb -P /tmp
#     - name: install pandoc
#       run: sudo dpkg -i /tmp/pandoc-2.13-1-amd64.deb
    - name: convert md to pdf
      run: pandoc --pdf-engine=xelatex -V mainfont='NanumMyeongjo' -V sansfond='NanumGothic' -V monofont='NanumGothic' -f markdown -o README.pdf README.md
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: kairos03
        author_email: kairos9603@gmail.com
        message: 'add converted pdf'
        add: '*.pdf'
