name: Convert PDF to Markdown

on:
  workflow_dispatch:
  push:
    paths:
    - '**.md'

jobs:
  convert_md: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 1
    - name: install dependency
      run: sudo apt-get update && sudo apt-get install -y fonts-nanum librsvg2-bin
    - name: donwload pandoc
      run: wget https://github.com/jgm/pandoc/releases/download/2.13/pandoc-2.13-1-amd64.deb -P /tmp
    - name: install pandoc
      run: sudo dpkg -i /tmp/pandoc-2.13-1-amd64.deb
    - name: convert md to pdf
      run: pandoc -f gfm --pdf-engine=xelatex -V mainfont='NanumMyeongjo' -V sansfond='NanumGothic' -V monofont='NanumGothic' -o README.pdf README.md
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.6.1
      env:
        # The token is built in to actions. No config required.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: Add .pdf files.
        PULL_REQUEST_TITLE: Add .pdf files.
        PULL_REQUEST_BRANCH: pdf-add
        PULL_REQUEST_BODY: Here are the .pdf files you requested.
        PULL_REQUEST_REVIEWERS: kairos03
